/**
 * Real-API smoke test.
 *
 * Drives the FULL moxxy stack — AnthropicProvider translator → loop strategy
 * → tool execution → event log projection — using a hand-authored Anthropic
 * stream fixture that mirrors the wire shape we'd record from a live API call.
 *
 * The fixture isn't generated by hitting the real API at test time; it's
 * captured shape that exercises every translation path. To regenerate from
 * a real run, use `apps/fixture-recorder` with MOXXY_FIXTURES=record.
 */
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { promises as fs } from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';
import {
  collectTurn,
  silentLogger,
  Session,
  autoAllowResolver,
} from '@moxxy/core';
import { defineProvider, definePlugin, defineTool } from '@moxxy/sdk';
import { toolUseModePlugin } from '@moxxy/mode-tool-use';
import { AnthropicProvider } from './provider.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface AnthropicStreamFixture {
  description: string;
  request: unknown;
  events: ReadonlyArray<Record<string, unknown>>;
}

/** Replays a fixture's raw Anthropic events as a fake SDK client. */
function fakeAnthropicClient(fixture: AnthropicStreamFixture): {
  messages: {
    stream: () => AsyncIterable<unknown>;
    countTokens: () => Promise<{ input_tokens: number }>;
  };
} {
  return {
    messages: {
      stream: () =>
        (async function* () {
          for (const e of fixture.events) yield e;
        })(),
      countTokens: async () => ({ input_tokens: 0 }),
    },
  };
}

let tmp: string;

beforeEach(async () => {
  tmp = await fs.mkdtemp(path.join(os.tmpdir(), 'mox-realapi-'));
});
afterEach(async () => {
  await fs.rm(tmp, { recursive: true, force: true });
});

describe('real-API smoke: tool-use turn replayed end-to-end', () => {
  it('translates raw Anthropic events through the full moxxy stack', async () => {
    const fixturePath = path.resolve(__dirname, '..', '__fixtures__', 'tool-use-turn.json');
    const fixture: AnthropicStreamFixture = JSON.parse(await fs.readFile(fixturePath, 'utf8'));

    const upstream = new AnthropicProvider({
      client: fakeAnthropicClient(fixture) as never,
    });

    // Need a second-turn reply for the model's summary AFTER the tool result.
    // For this smoke we only assert on the first translation pass, so wire a
    // shim that exits the loop on its second invocation.
    let callCount = 0;
    const provider = {
      name: upstream.name,
      models: upstream.models,
      async *stream(req: import('@moxxy/sdk').ProviderRequest) {
        callCount += 1;
        if (callCount === 1) {
          yield* upstream.stream(req);
          return;
        }
        // Second call: emit a clean end_turn so the loop terminates.
        yield { type: 'message_start' as const, model: req.model };
        yield { type: 'text_delta' as const, delta: 'OK — greeted world.' };
        yield { type: 'message_end' as const, stopReason: 'end_turn' as const };
      },
      async countTokens() {
        return 0;
      },
    };

    const session = new Session({
      cwd: tmp,
      logger: silentLogger,
      permissionResolver: autoAllowResolver,
    });
    session.pluginHost.registerStatic(
      definePlugin({
        name: 'realapi-shim',
        providers: [
          defineProvider({
            name: 'anthropic',
            models: [...upstream.models],
            createClient: () => provider,
          }),
        ],
      }),
    );
    session.providers.setActive('anthropic');
    session.pluginHost.registerStatic(toolUseModePlugin);
    session.pluginHost.registerStatic(
      definePlugin({
        name: 'realapi-tools',
        tools: [
          defineTool({
            name: 'greet',
            description: 'Returns a greeting for the given name.',
            inputSchema: z.object({ name: z.string() }),
            handler: ({ name }) => `Hello, ${name}!`,
          }),
        ],
      }),
    );

    const events = await collectTurn(session, 'please greet world');

    // Phase 1: AnthropicProvider correctly translated the raw stream into a
    // tool_use event sequence with the streamed input JSON re-assembled.
    const toolStart = events.find((e) => e.type === 'tool_call_requested');
    if (toolStart?.type !== 'tool_call_requested') throw new Error('expected tool_call_requested');
    expect(toolStart.name).toBe('greet');
    expect(toolStart.input).toEqual({ name: 'world' });
    expect(toolStart.callId).toBe('toolu_01XYZ');

    // Phase 2: the tool executed and the result fed back into the loop.
    const toolResult = events.find((e) => e.type === 'tool_result');
    if (toolResult?.type !== 'tool_result') throw new Error('expected tool_result');
    expect(toolResult.ok).toBe(true);
    expect(toolResult.output).toBe('Hello, world!');

    // Phase 3: model produced a final summary in the second iteration.
    const finalAssistant = events.filter((e) => e.type === 'assistant_message').pop();
    if (finalAssistant?.type !== 'assistant_message') throw new Error('expected assistant_message');
    expect(finalAssistant.content).toContain('greeted');

    // The translator emitted exactly one provider request (not retried).
    const providerRequests = events.filter((e) => e.type === 'provider_request');
    expect(providerRequests.length).toBe(2); // one per loop iteration
  });
});
