/**
 * Build-time generator: compile every workspace package's
 * `package.json#moxxy.requirements` into a static TS module so requirement
 * gating + load-order toposort survive bundling.
 *
 * Why this exists: once @moxxy/cli is bundled and published as a single
 * binary, the bundled packages have no on-disk `package.json`, so the
 * runtime disk lookup (`readPackageMoxxyRequirements`) returns `[]` for them
 * — silently disabling hard-requirement gating (e.g. @moxxy/plugin-stt-whisper-codex).
 * This manifest is consulted first; the disk lookup remains the fallback for
 * third-party / from-source plugins.
 *
 * Run automatically by the cli `build` script (before tsup). The output is
 * committed so `tsc --noEmit` typecheck works without running the generator.
 */
import { promises as fs } from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, '..', '..', '..');
const packagesDir = path.join(repoRoot, 'packages');
const outFile = path.join(here, '..', 'src', 'setup', 'builtin-requirements.generated.ts');

interface Requirement {
  kind: string;
  name: string;
  [k: string]: unknown;
}

async function main(): Promise<void> {
  const entries = await fs.readdir(packagesDir, { withFileTypes: true });
  const manifest: Record<string, Requirement[]> = {};

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const pkgJsonPath = path.join(packagesDir, entry.name, 'package.json');
    let pkg: { name?: string; moxxy?: { requirements?: Requirement[] } };
    try {
      pkg = JSON.parse(await fs.readFile(pkgJsonPath, 'utf8'));
    } catch {
      continue;
    }
    const reqs = pkg.moxxy?.requirements;
    if (pkg.name && Array.isArray(reqs) && reqs.length > 0) {
      manifest[pkg.name] = reqs;
    }
  }

  // Deterministic key order so the committed file has a stable diff.
  const sorted = Object.fromEntries(
    Object.entries(manifest).sort(([a], [b]) => a.localeCompare(b)),
  );

  const body = `// AUTO-GENERATED by scripts/gen-requirements.mts — DO NOT EDIT.
// Compiles each bundled package's package.json#moxxy.requirements into the
// binary so requirement gating + toposort survive bundling. Regenerated by
// the cli \`build\` script; committed so typecheck works standalone.
import type { MoxxyRequirement } from '@moxxy/sdk';

export const BUILTIN_REQUIREMENTS: Readonly<
  Record<string, ReadonlyArray<MoxxyRequirement>>
> = ${JSON.stringify(sorted, null, 2)} as const satisfies Readonly<
  Record<string, ReadonlyArray<MoxxyRequirement>>
>;
`;

  await fs.writeFile(outFile, body, 'utf8');
  const count = Object.keys(sorted).length;
  console.log(`gen-requirements: wrote ${count} package(s) to ${path.relative(repoRoot, outFile)}`);
}

main().catch((err) => {
  console.error('gen-requirements failed:', err);
  process.exit(1);
});
