/**
 * Pure helpers for the moxxy interactive setup. The interactive UX lives in
 * `@moxxy/cli`'s wizard runner; this module only owns serializing the user's
 * selections into a `moxxy.config.yaml` body, so the renderer can be unit-
 * tested without spinning up a terminal.
 */

/** How the wizard authenticates a given provider. */
export type ProviderAuthKind = 'apiKey' | 'oauth';

export interface SetupChoice {
  readonly id: string;
  readonly label: string;
  readonly description?: string;
  /** When true, the option is rendered but cannot be selected (with the disabled reason). */
  readonly disabled?: string;
}

export interface SetupSelections {
  readonly providers: ReadonlyArray<string>;
  readonly apiKeys: Record<string, string>;
  readonly primary: string;
  readonly model: string | null;
  readonly mode: string;
  readonly embedder: string;
  /** Optional per-provider auth kind. Missing entries default to `'apiKey'`. */
  readonly authKinds?: Record<string, ProviderAuthKind>;
  /**
   * Opt-in plugin-security selection. Omit to leave the security block
   * out of the generated YAML entirely (= default, off behavior).
   */
  readonly security?: {
    readonly enabled: boolean;
    readonly isolator?: string;
  };
}

function isOAuth(sel: SetupSelections, providerId: string): boolean {
  return sel.authKinds?.[providerId] === 'oauth';
}

export function renderYaml(sel: SetupSelections): string {
  const fallbacks = sel.providers.filter((p) => p !== sel.primary);
  const lines: string[] = ['# moxxy.config.yaml — generated by `moxxy init`', ''];
  lines.push('provider:');
  lines.push(`  name: ${sel.primary}`);
  if (sel.model) lines.push(`  model: ${sel.model}`);
  // OAuth providers (e.g. openai-codex) authenticate via tokens stored in the
  // vault under a provider-specific key — they don't take an `apiKey`.
  if (!isOAuth(sel, sel.primary)) {
    lines.push('  config:');
    lines.push(`    apiKey: \${vault:${sel.primary.toUpperCase()}_API_KEY}`);
  }
  if (fallbacks.length > 0) {
    lines.push('  fallbacks:');
    for (const f of fallbacks) lines.push(`    - ${f}`);
  }
  lines.push('');
  lines.push(`mode: ${sel.mode}`);
  if (sel.embedder !== 'tfidf') {
    lines.push('embeddings:');
    lines.push(`  provider: ${sel.embedder}`);
  }
  if (sel.security?.enabled) {
    lines.push('security:');
    lines.push('  enabled: true');
    if (sel.security.isolator && sel.security.isolator !== 'inproc') {
      lines.push(`  isolator: ${sel.security.isolator}`);
    }
  }
  lines.push('');
  return lines.join('\n');
}
